FROM node:alpine3.15 AS builder
WORKDIR /tmp
COPY package.json ./
COPY tsconfig.json ./
COPY src ./src
RUN ls -a
RUN npm install
RUN npm run build

FROM node:alpine3.15
ENV PORT=8080
ENV OWNER="steve"
ENV ENVIRONMENT="production"
WORKDIR /app
COPY package.json ./
RUN npm install --omit=dev
COPY --from=builder /tmp/build .
RUN npm install pm2 -g
EXPOSE 8080
CMD ["pm2-runtime","app.js"]